/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'fe'}],

  // But you can create a sidebar manually
  storySideBar: [{type: 'autogenerated', dirName: 'story'}],
  backendSideBar: [{type: 'autogenerated', dirName: 'backend'}],
  // feArchitectureSideBar: [{type: 'autogenerated', dirName: 'fe_architecture'}],
  // feEcosystemSideBar: [{type: 'autogenerated', dirName: 'fe_ecosystem'}],
};

module.exports = sidebars;
